import { Button } from '@/components/ui/button'
import { Card, CardContent, CardFooter } from '@/components/ui/card'
import Image from 'next/image'

interface ImageGalleryProps {
  images: Array<{ model: string; url: string }>
  selectedImage: string | null
  onSelectImage: (url: string) => void
}

export function ImageGallery({ images, selectedImage, onSelectImage }: ImageGalleryProps) {
  return (
    <div className="mt-6 grid grid-cols-1 sm:grid-cols-3 gap-4">
      {images.map(({ model, url }, index) => (
        <Card key={index} className={selectedImage === url ? 'border-4 border-blue-500' : ''}>
          <CardContent>
            {/* <img src={url || "/placeholder.svg"} alt={`Generated by ${model}`} className="w-full h-auto" /> */}
            <Image
              src={url || '/placeholder.svg'}
              alt={`Generated by ${model}`}
              width={512}
              height={512}
              className="w-full h-auto"
            />
          </CardContent>
          <CardFooter>
            <p className="text-center text-sm font-medium">{model}</p>
            <Button onClick={() => onSelectImage(url)} className="mt-2 w-full">
              Select Image
            </Button>
          </CardFooter>
        </Card>
      ))}
    </div>
  )
}
